(()=>{
const root=document.documentElement;
const stored=()=>{try{return localStorage.getItem('athar-lang')||localStorage.getItem('athar.lang')||'en'}catch(e){return'en'}};
const lang=()=>root.lang==='ar'?'ar':'en';
function apply(l){l=l==='ar'?'ar':'en';root.lang=l;root.dir=l==='ar'?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(el=>{el.textContent=el.dataset[l]});document.querySelectorAll('[data-placeholder-en][data-placeholder-ar]').forEach(el=>{el.placeholder=l==='ar'?el.dataset.placeholderAr:el.dataset.placeholderEn});document.querySelectorAll('[data-lang]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.lang===l)));try{localStorage.setItem('athar-lang',l)}catch(e){}}
function message(form,en,ar,type='info'){const el=form?.querySelector('.form-message')||form;if(!el)return;el.dataset.en=en;el.dataset.ar=ar;el.textContent=lang()==='ar'?ar:en;el.dataset.state=type;el.classList.add('show');el.focus?.()}
function busy(form,on){const b=form?.querySelector('button[type="submit"]');if(!b)return;b.disabled=on;b.setAttribute('aria-busy',String(on));}
function pageUrl(file){const base=location.pathname.replace(/[^/]*$/,'');return `${location.origin}${base}${file}`}
let sb=null;
function client(){if(sb)return sb;if(!window.supabase||!window.ATHAR_SUPABASE)throw new Error('backend_unavailable');sb=window.supabase.createClient(window.ATHAR_SUPABASE.url,window.ATHAR_SUPABASE.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
async function register(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();const password=form.querySelector('#password').value;const displayName=form.querySelector('#name').value.trim();const preferredLanguage=lang();const {data,error}=await c.auth.signUp({email,password,options:{data:{display_name:displayName,preferred_language:preferredLanguage},emailRedirectTo:pageUrl('login.html?verified=1')}});if(error)throw error;if(data.session){location.href='account.html';return}message(form,'Account created. Check your email to verify the adult account, then sign in.','تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد حساب البالغ، ثم سجّل الدخول.','success')}catch(e){message(form,'We could not create the account. Check the details and try again.','تعذر إنشاء الحساب. تحقق من البيانات وحاول مرة أخرى.','error')}finally{busy(form,false)}}
async function login(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();const password=form.querySelector('#password').value;const {error}=await c.auth.signInWithPassword({email,password});if(error)throw error;const next=new URLSearchParams(location.search).get('next');location.href=next==='child-profile'?'child-profile.html':'account.html'}catch(e){message(form,'Sign-in was not successful. Check the email and password, or use account recovery.','لم ينجح تسجيل الدخول. تحقق من البريد الإلكتروني وكلمة المرور أو استخدم استعادة الحساب.','error')}finally{busy(form,false)}}
async function recover(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();await c.auth.resetPasswordForEmail(email,{redirectTo:pageUrl('account-help.html?mode=reset')});message(form,'If an adult account is eligible for recovery, instructions have been sent.','إذا كان حساب البالغ مؤهلاً للاستعادة، فقد تم إرسال التعليمات.','success')}catch(e){message(form,'If an adult account is eligible for recovery, instructions will be sent.','إذا كان حساب البالغ مؤهلاً للاستعادة، فسيتم إرسال التعليمات.','success')}finally{busy(form,false)}}
async function updatePassword(form){busy(form,true);try{const c=client();const password=form.querySelector('#new-password').value;const confirm=form.querySelector('#confirm-password').value;if(password!==confirm){message(form,'The passwords do not match.','كلمتا المرور غير متطابقتين.','error');return}const {error}=await c.auth.updateUser({password});if(error)throw error;message(form,'Password updated. You can now sign in with the new password.','تم تحديث كلمة المرور. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.','success');setTimeout(()=>location.href='login.html',900)}catch(e){message(form,'We could not update the password. Request a new recovery link and try again.','تعذر تحديث كلمة المرور. اطلب رابط استعادة جديداً وحاول مرة أخرى.','error')}finally{busy(form,false)}}
async function createChild(form){busy(form,true);try{const c=client();const {data:{session}}=await c.auth.getSession();if(!session){location.href='login.html?next=child-profile';return}const payload={nickname:form.querySelector('#display').value.trim(),age_band:form.querySelector('#age').value,preferred_language:form.querySelector('#lang').value,adult_consent:form.querySelector('#adult-consent').checked,child_assent:form.querySelector('#child-assent').checked};const {data,error}=await c.functions.invoke('create-child-profile',{body:payload});if(error)throw error;message(form,`Child profile “${data.child.nickname}” created with recorded consent and assent.`,`تم إنشاء ملف الطفل «${data.child.nickname}» مع تسجيل موافقة البالغ وموافقة الطفل.`,'success');setTimeout(()=>location.href='account.html',700)}catch(e){message(form,'The child profile could not be created. Confirm you are signed in as the authorized parent or guardian and try again.','تعذر إنشاء ملف الطفل. تأكد من تسجيل الدخول بصفتك ولي الأمر أو الوصي المصرح له ثم حاول مرة أخرى.','error')}finally{busy(form,false)}}
async function requireSession(next='account'){try{const {data:{session}}=await client().auth.getSession();if(!session){location.href=`login.html?next=${encodeURIComponent(next)}`;return null}return session}catch(e){location.href='login.html';return null}}
async function guardChildPage(){if(!document.querySelector('[data-account-action="child-profile"]'))return;await requireSession('child-profile')}
async function signOut(){try{sessionStorage.removeItem('athar.activeChildProfile');await client().auth.signOut()}finally{location.href='login.html'}}
function recoveryMode(){const reset=document.querySelector('[data-account-action="update-password"]');const request=document.querySelector('[data-account-action="recover"]');if(!reset||!request)return;const show=()=>{request.hidden=true;reset.hidden=false};if(new URLSearchParams(location.search).get('mode')==='reset')show();try{client().auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')show()})}catch(e){}}
function pill(text,state){const s=document.createElement('span');s.className='pill'+(state?` ${state}`:'');s.textContent=text;return s}
function actionButton(label,action,id,danger=false){const b=document.createElement('button');b.type='button';b.className='profile-action'+(danger?' danger':'');b.dataset.profileAction=action;b.dataset.childId=id;b.textContent=label;return b}
function profileCard(row){const card=document.createElement('article');card.className='profile-card';card.dataset.childId=row.id;const h=document.createElement('h3');h.textContent=row.nickname;card.appendChild(h);const meta=document.createElement('div');meta.className='profile-meta';meta.appendChild(pill(lang()==='ar'?`العمر ${row.age_band}`:`Ages ${row.age_band}`));meta.appendChild(pill(row.preferred_language==='ar'?'العربية':'English'));const consent=row.consent_status||'unknown';const assent=row.assent_status||'unknown';meta.appendChild(pill(lang()==='ar'?`موافقة البالغ: ${consent}`:`Adult consent: ${consent}`,consent==='granted'?'':'warn'));meta.appendChild(pill(lang()==='ar'?`موافقة الطفل: ${assent}`:`Child assent: ${assent}`,assent==='assented'?'':'warn'));if(row.archived_at)meta.appendChild(pill(lang()==='ar'?'موقوف':'Archived','off'));card.appendChild(meta);const actions=document.createElement('div');actions.className='profile-actions';const use=actionButton(lang()==='ar'?'استخدم هذا الملف':'Use this profile','select',row.id);if(row.archived_at)use.disabled=true;actions.appendChild(use);if(!row.archived_at&&consent==='granted')actions.appendChild(actionButton(lang()==='ar'?'سحب موافقة البالغ':'Withdraw adult consent','withdraw-consent',row.id,true));if(!row.archived_at&&assent==='assented')actions.appendChild(actionButton(lang()==='ar'?'سحب موافقة الطفل':'Withdraw child assent','withdraw-assent',row.id,true));actions.appendChild(actionButton(lang()==='ar'?'طلب نسخة من البيانات':'Request data export','request-export',row.id));actions.appendChild(actionButton(lang()==='ar'?'طلب حذف الملف':'Request deletion','request-delete',row.id,true));card.appendChild(actions);return card}
async function loadAccountPage(){const list=document.querySelector('[data-child-profile-list]');if(!list)return;const session=await requireSession('account');if(!session)return;const msg=document.querySelector('[data-account-page-message]');try{const c=client();const {data,error}=await c.from('child_profile_status').select('id,nickname,age_band,preferred_language,created_at,archived_at,consent_status,assent_status').order('created_at',{ascending:true});if(error)throw error;list.replaceChildren();if(!data?.length){const empty=document.createElement('div');empty.className='empty-state';empty.textContent=lang()==='ar'?'لا توجد ملفات أطفال مصرح بها بعد. أنشئ ملف اختبار غير مُعرّف للهوية للمتابعة.':'No authorized child profiles yet. Add a non-identifying test profile to continue.';list.appendChild(empty);return}data.forEach(row=>list.appendChild(profileCard(row)))}catch(e){list.replaceChildren();message(msg,'We could not load the authorized profiles. Please sign in again or retry.','تعذر تحميل الملفات المصرح بها. سجّل الدخول مجدداً أو أعد المحاولة.','error')}}
async function manageProfile(button){const action=button.dataset.profileAction;const id=button.dataset.childId;if(!action||!id)return;if(action==='select'){sessionStorage.setItem('athar.activeChildProfile',id);location.href='learn.html';return}const destructive=action==='withdraw-consent'||action==='withdraw-assent'||action==='request-delete';if(destructive){const ok=confirm(lang()==='ar'?'هل تريد المتابعة؟ سيُسجل هذا الإجراء في بيئة التطوير.':'Continue? This action will be recorded in the development environment.');if(!ok)return}button.disabled=true;try{const c=client();const {error}=await c.functions.invoke('manage-child-profile',{body:{child_profile_id:id,action}});if(error)throw error;const msg=document.querySelector('[data-account-page-message]');const copy={
'withdraw-consent':['Adult consent was withdrawn and the profile was archived.','تم سحب موافقة البالغ وإيقاف الملف.'],
'withdraw-assent':['Child assent was withdrawn and the profile was archived.','تم سحب موافقة الطفل وإيقاف الملف.'],
'request-export':['A data export request was recorded for controlled processing.','تم تسجيل طلب نسخة من البيانات للمعالجة المنضبطة.'],
'request-delete':['A deletion request was recorded for controlled processing.','تم تسجيل طلب حذف للمعالجة المنضبطة.']};const text=copy[action]||['Request completed.','اكتمل الطلب.'];message(msg,text[0],text[1],'success');await loadAccountPage()}catch(e){const msg=document.querySelector('[data-account-page-message]');message(msg,'The account action could not be completed. No change was assumed.','تعذر إكمال إجراء الحساب. لم يُفترض حدوث أي تغيير.','error')}finally{button.disabled=false}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(b){apply(b.dataset.lang);if(document.querySelector('[data-child-profile-list]'))loadAccountPage()}const so=e.target.closest('[data-account-signout]');if(so){e.preventDefault();signOut()}const pa=e.target.closest('[data-profile-action]');if(pa)manageProfile(pa)});
document.addEventListener('submit',e=>{const form=e.target.closest('[data-account-action]');if(!form)return;e.preventDefault();const action=form.dataset.accountAction;if(action==='register')register(form);else if(action==='login')login(form);else if(action==='recover')recover(form);else if(action==='update-password')updatePassword(form);else if(action==='child-profile')createChild(form)});
document.addEventListener('DOMContentLoaded',()=>{apply(stored());recoveryMode();guardChildPage();loadAccountPage();if(new URLSearchParams(location.search).get('verified')==='1'){const form=document.querySelector('[data-account-action="login"]');message(form,'Email verified. Sign in to continue.','تم التحقق من البريد الإلكتروني. سجّل الدخول للمتابعة.','success')}});
})();