(()=>{
const root=document.documentElement;
const stored=()=>{try{return localStorage.getItem('athar-lang')||localStorage.getItem('athar.lang')||'en'}catch(e){return'en'}};
const lang=()=>root.lang==='ar'?'ar':'en';
function apply(l){l=l==='ar'?'ar':'en';root.lang=l;root.dir=l==='ar'?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(el=>{el.textContent=el.dataset[l]});document.querySelectorAll('[data-placeholder-en][data-placeholder-ar]').forEach(el=>{el.placeholder=l==='ar'?el.dataset.placeholderAr:el.dataset.placeholderEn});document.querySelectorAll('[data-lang]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.lang===l)));try{localStorage.setItem('athar-lang',l)}catch(e){}}
function message(form,en,ar,type='info'){const el=form?.querySelector('.form-message');if(!el)return;el.dataset.en=en;el.dataset.ar=ar;el.textContent=lang()==='ar'?ar:en;el.dataset.state=type;el.classList.add('show');el.focus?.()}
function busy(form,on){const b=form?.querySelector('button[type="submit"]');if(!b)return;b.disabled=on;b.setAttribute('aria-busy',String(on));}
function pageUrl(file){const base=location.pathname.replace(/[^/]*$/,'');return `${location.origin}${base}${file}`}
let sb=null;
function client(){if(sb)return sb;if(!window.supabase||!window.ATHAR_SUPABASE)throw new Error('backend_unavailable');sb=window.supabase.createClient(window.ATHAR_SUPABASE.url,window.ATHAR_SUPABASE.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
async function register(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();const password=form.querySelector('#password').value;const displayName=form.querySelector('#name').value.trim();const preferredLanguage=lang();const {data,error}=await c.auth.signUp({email,password,options:{data:{display_name:displayName,preferred_language:preferredLanguage},emailRedirectTo:pageUrl('login.html?verified=1')}});if(error)throw error;if(data.session){location.href='child-profile.html';return}message(form,'Account created. Check your email to verify the adult account, then sign in.','تم إنشاء الحساب. تحقق من بريدك الإلكتروني لتأكيد حساب البالغ، ثم سجّل الدخول.','success')}catch(e){message(form,'We could not create the account. Check the details and try again.','تعذر إنشاء الحساب. تحقق من البيانات وحاول مرة أخرى.','error')}finally{busy(form,false)}}
async function login(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();const password=form.querySelector('#password').value;const {error}=await c.auth.signInWithPassword({email,password});if(error)throw error;location.href='child-profile.html'}catch(e){message(form,'Sign-in was not successful. Check the email and password, or use account recovery.','لم ينجح تسجيل الدخول. تحقق من البريد الإلكتروني وكلمة المرور أو استخدم استعادة الحساب.','error')}finally{busy(form,false)}}
async function recover(form){busy(form,true);try{const c=client();const email=form.querySelector('#email').value.trim();await c.auth.resetPasswordForEmail(email,{redirectTo:pageUrl('account-help.html?mode=reset')});message(form,'If an adult account is eligible for recovery, instructions have been sent.','إذا كان حساب البالغ مؤهلاً للاستعادة، فقد تم إرسال التعليمات.','success')}catch(e){message(form,'If an adult account is eligible for recovery, instructions will be sent.','إذا كان حساب البالغ مؤهلاً للاستعادة، فسيتم إرسال التعليمات.','success')}finally{busy(form,false)}}
async function updatePassword(form){busy(form,true);try{const c=client();const password=form.querySelector('#new-password').value;const confirm=form.querySelector('#confirm-password').value;if(password!==confirm){message(form,'The passwords do not match.','كلمتا المرور غير متطابقتين.','error');return}const {error}=await c.auth.updateUser({password});if(error)throw error;message(form,'Password updated. You can now sign in with the new password.','تم تحديث كلمة المرور. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.','success');setTimeout(()=>location.href='login.html',900)}catch(e){message(form,'We could not update the password. Request a new recovery link and try again.','تعذر تحديث كلمة المرور. اطلب رابط استعادة جديداً وحاول مرة أخرى.','error')}finally{busy(form,false)}}
async function createChild(form){busy(form,true);try{const c=client();const {data:{session}}=await c.auth.getSession();if(!session){location.href='login.html?next=child-profile';return}const payload={nickname:form.querySelector('#display').value.trim(),age_band:form.querySelector('#age').value,preferred_language:form.querySelector('#lang').value,adult_consent:form.querySelector('#adult-consent').checked,child_assent:form.querySelector('#child-assent').checked};const {data,error}=await c.functions.invoke('create-child-profile',{body:payload});if(error)throw error;message(form,`Child profile “${data.child.nickname}” created with recorded consent and assent.`,`تم إنشاء ملف الطفل «${data.child.nickname}» مع تسجيل موافقة البالغ وموافقة الطفل.`,'success');form.reset()}catch(e){message(form,'The child profile could not be created. Confirm you are signed in as the authorized parent or guardian and try again.','تعذر إنشاء ملف الطفل. تأكد من تسجيل الدخول بصفتك ولي الأمر أو الوصي المصرح له ثم حاول مرة أخرى.','error')}finally{busy(form,false)}}
async function guardChildPage(){if(!document.querySelector('[data-account-action="child-profile"]'))return;try{const {data:{session}}=await client().auth.getSession();if(!session)location.href='login.html?next=child-profile'}catch(e){location.href='login.html?next=child-profile'}}
async function signOut(){try{await client().auth.signOut()}finally{location.href='login.html'}}
function recoveryMode(){const reset=document.querySelector('[data-account-action="update-password"]');const request=document.querySelector('[data-account-action="recover"]');if(!reset||!request)return;const show=()=>{request.hidden=true;reset.hidden=false};if(new URLSearchParams(location.search).get('mode')==='reset')show();try{client().auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')show()})}catch(e){}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(b)apply(b.dataset.lang);const so=e.target.closest('[data-account-signout]');if(so){e.preventDefault();signOut()}});
document.addEventListener('submit',e=>{const form=e.target.closest('[data-account-action]');if(!form)return;e.preventDefault();const action=form.dataset.accountAction;if(action==='register')register(form);else if(action==='login')login(form);else if(action==='recover')recover(form);else if(action==='update-password')updatePassword(form);else if(action==='child-profile')createChild(form)});
document.addEventListener('DOMContentLoaded',()=>{apply(stored());recoveryMode();guardChildPage();if(new URLSearchParams(location.search).get('verified')==='1'){const form=document.querySelector('[data-account-action="login"]');message(form,'Email verified. Sign in to continue.','تم التحقق من البريد الإلكتروني. سجّل الدخول للمتابعة.','success')}});
})();