const {test,expect}=require('@playwright/test');
async function noHorizontalOverflow(page){return page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1)}
const publicPages=['/index.html','/learn.html','/families.html','/schools.html','/safety.html'];
for(const width of [390,768,1280])test(`core product surfaces render without horizontal overflow at ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});for(const path of publicPages){const errors=[];const onError=e=>errors.push(String(e));page.on('pageerror',onError);await page.goto(path);expect(await noHorizontalOverflow(page),`${path} overflow at ${width}px`).toBeTruthy();expect(errors).toEqual([]);page.off('pageerror',onError)}});
test('homepage keeps all trust-critical navigation reachable on phone',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/index.html');await expect(page.locator('.nav a')).toHaveCount(5);await expect(page.locator('.nav a[href="families.html"]')).toBeVisible();await expect(page.locator('.nav a[href="schools.html"]')).toBeVisible();await expect(page.locator('.nav a[href="safety.html"]')).toBeVisible()});
test('homepage exposes role-aware learner family and educator entry',async({page})=>{await page.goto('/index.html');await expect(page.locator('#roles .role-card')).toHaveCount(3);await expect(page.locator('#roles .role-card[href="learn.html"]')).toBeVisible();await expect(page.locator('#roles .role-card[href="families.html"]')).toBeVisible();await expect(page.locator('#roles .role-card[href="schools.html"]')).toBeVisible()});
test('homepage restores Arabic before visible content and fully localizes safety pills',async({page})=>{await page.addInitScript(()=>localStorage.setItem('athar-lang','ar'));await page.setViewportSize({width:390,height:844});await page.goto('/index.html');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.locator('html')).toHaveAttribute('lang','ar');await expect(page.locator('.safe-pills')).toContainText('الوقاية');await expect(page.locator('.safe-pills')).toContainText('الكشف');await expect(page.locator('.safe-pills')).toContainText('الاستجابة');await expect(page.locator('.safe-pills')).toContainText('التعافي');await expect(page.locator('.safe-pills')).toContainText('التحقق');await expect(page.locator('.safe-pills')).toContainText('جواز السلامة');await expect(page.locator('.safe-pills')).not.toContainText('Prevent')});
test('mobile homepage journey is vertical rather than horizontally scrollable',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/index.html');const layout=await page.locator('.trace').evaluate(el=>({cols:getComputedStyle(el).gridTemplateColumns,sw:el.scrollWidth,cw:el.clientWidth}));expect(layout.sw).toBeLessThanOrEqual(layout.cw+1);expect(layout.cols.split(' ').length).toBe(1)});
test('journey exposes all 16 missions, one pilot cohort and companion choices',async({page})=>{await page.setViewportSize({width:1280,height:900});await page.goto('/learn.html');await expect(page.locator('.mission')).toHaveCount(16);await expect(page.locator('button.age-choice')).toHaveCount(0);await expect(page.getByText('Pilot cohort: ages 10–12.')).toBeVisible();await expect(page.locator('button.companion-choice[data-companion="hamdan"]')).toBeVisible();await expect(page.locator('button.companion-choice[data-companion="hessa"]')).toBeVisible();await expect(page.locator('button.companion-choice[data-companion="none"]')).toBeVisible()});
test('mission player keeps primary action dock visible on phone and desktop',async({page})=>{for(const viewport of [{width:390,height:844},{width:1280,height:900}]){await page.setViewportSize(viewport);await page.goto('/lesson.html?m=what-is-ai');await expect(page.locator('.stagetitle')).toBeVisible();await expect(page.locator('.actionbar')).toBeVisible();const box=await page.locator('.actionbar').boundingBox();expect(box).not.toBeNull();expect(box.y+box.height).toBeLessThanOrEqual(viewport.height+4);expect(await noHorizontalOverflow(page)).toBeTruthy()}});
test('family view communicates evidence without surveillance',async({page})=>{await page.goto('/families.html');await expect(page.getByText('Progress, not profiling')).toBeVisible();await expect(page.getByText('Evidence, not transcripts')).toBeVisible();await expect(page.locator('#adultProgress .adult-metric')).toHaveCount(5);await expect(page.locator('.family-card')).toHaveCount(3);await expect(page.locator('.boundary-grid .boundary')).toHaveCount(2)});
test('educator view presents complete foundation and future school gates honestly',async({page})=>{await page.goto('/schools.html');await expect(page.locator('.track-overview article')).toHaveCount(6);await expect(page.locator('.educator-facts span')).toHaveCount(4);await expect(page.locator('.pilot-grid article')).toHaveCount(3);await expect(page.getByText('Cohort & assignment layer')).toBeVisible();await expect(page.getByText('Identity & consent')).toBeVisible()});
test('Arabic parity holds across child journey family educator and safety surfaces',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/ar/learn.html');await expect(page.locator('html')).toHaveAttribute('dir','rtl');expect(await noHorizontalOverflow(page)).toBeTruthy();for(const path of ['/families.html','/schools.html','/safety.html']){await page.goto(path);const ar=page.locator('button[data-lang="ar"]');await expect(ar).toBeVisible();await ar.click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.locator('html')).toHaveAttribute('lang','ar');expect(await noHorizontalOverflow(page),`${path} overflows in Arabic at phone width`).toBeTruthy()}});
test('family and educator summaries do not expose raw answer UI',async({page})=>{for(const path of ['/families.html','/schools.html']){await page.goto(path);await expect(page.locator('textarea')).toHaveCount(0);await expect(page.locator('input[type="text"]')).toHaveCount(0);await expect(page.locator('#adultProgress')).toBeVisible()}});