const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='athar.lesson1.v2';
const defaults={stage:0,lang:'en',age:'7-9',companion:'none',done:[],evidence:{recognition:'not-yet',patterns:'not-yet',verification:'not-yet',privacy:'not-yet',agency:'not-yet'},hints:{},missionStep:0,completed:false};
function safeLoad(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaults,...x,evidence:{...defaults.evidence,...(x.evidence||{})},hints:x.hints||{},done:Array.isArray(x.done)?x.done:[]}}catch{return {...defaults}}}
const state=safeLoad(); state.lang=localStorage.getItem('athar.lesson.lang')||state.lang; state.age=localStorage.getItem('athar.lesson.age')||state.age; state.companion=localStorage.getItem('athar.companion')||state.companion;
const copy=(en,ar)=>state.lang==='ar'?ar:en; const older=()=>state.age==='10-12';
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem('athar.lesson.lang',state.lang);localStorage.setItem('athar.lesson.age',state.age);localStorage.setItem('athar.companion',state.companion)}
function mark(k){state.evidence[k]=state.hints[k]?'supported':'independent';save()}
function deep(en,ar){return older()?`<details class="deep"><summary>${copy('Tell me more','أخبرني أكثر')}</summary><p>${copy(en,ar)}</p></details>`:''}
const title=[['Mission Entry','بداية المهمة'],['Where Have You Seen AI?','أين رأيت الذكاء الاصطناعي؟'],['So, What Is AI?','إذن، ما هو الذكاء الاصطناعي؟'],['Human, Computer or AI?','إنسان، حاسوب أم ذكاء اصطناعي؟'],['What Can AI Do?','ماذا يستطيع الذكاء الاصطناعي أن يفعل؟'],['Teach the AI','علّم الذكاء الاصطناعي'],['Can AI Be Wrong?','هل يمكن للذكاء الاصطناعي أن يخطئ؟'],['My Three Smart AI Rules','قواعدي الثلاث للاستخدام الذكي'],['Your First AI Mission','مهمتك الأولى في الذكاء الاصطناعي'],['My First AI Discovery','اكتشافي الأول في الذكاء الاصطناعي']];
function shell(body,dark=false){return `<article class="stage-card ${dark?'dark':''}"><div><span class="stage-badge">Stage ${String(state.stage).padStart(2,'0')}</span>${body}</div>${companionSlot()}</article>`}
function nav(label,action='next'){return `<div class="actions">${state.stage?`<button class="secondary" data-action="back">${copy('Back','السابق')}</button>`:'<span></span>'}<button class="primary" data-action="${action}">${label||copy('Continue','متابعة')}</button></div>`}
function multi(items,key){return `<div class="grid">${items.map((x,i)=>{const [ic,en,ar,ans]=x;return `<button class="choice" data-multi="${key}" data-answer="${ans}" data-i="${i}"><span class="icon">${ic}</span><b>${copy(en,ar)}</b></button>`}).join('')}</div>`}
function single(items,key){return `<div class="grid">${items.map((x,i)=>`<button class="answer-card" data-single="${key}" data-i="${i}"><span class="icon">${x[0]}</span><b>${copy(x[1],x[2])}</b></button>`).join('')}</div>`}
function companionSlot(){if(state.companion==='none')return `<div class="companion-slot empty" aria-hidden="true"></div>`;return `<div class="companion-slot"><img id="stageCompanion" alt="${state.companion==='hamdan'?'Hamdan':'Hessa'}"></div>`}
function stageBody(){switch(state.stage){
case 0:return `<h1>What Is AI?<span class="arabic-title">ما هو الذكاء الاصطناعي؟</span></h1><p class="lede">${copy('Discover where AI appears, how examples and patterns matter, and how to use AI wisely.','اكتشف أين يظهر الذكاء الاصطناعي، وكيف تؤثر الأمثلة والأنماط، وكيف تستخدمه بوعي.')}</p><div class="journey-map"><span>${copy('Find AI','أتعرف إلى الذكاء الاصطناعي')}</span><span>${copy('Understand it','أفهمه')}</span><span>${copy('Try it','أجرّبه')}</span><span>${copy('Check it','أتحقق')}</span><span>${copy('Use it wisely','أستخدمه بوعي')}</span></div><div class="feedback info"><strong>${copy('Your role','دورك')}</strong>${copy('You remain the thinker. AI remains the tool.','أنت تفكر وتقرر. والذكاء الاصطناعي أداة تساعدك.')}</div>${nav()}`;
case 1:return `<h1>${copy(...title[1])}</h1><p class="lede">${copy('Tap everything you think might use AI.','اضغط على كل شيء تعتقد أنه قد يستخدم الذكاء الاصطناعي.')}</p>${multi([['📱','Phone understands voice','هاتف يفهم صوتك','1'],['🗺️','Map suggests best route','خريطة تقترح أفضل طريق','1'],['📷','Camera recognises a face or object','كاميرا تتعرّف إلى وجه أو شيء','1'],['🤖','Robot adapts where to move','روبوت يكيّف طريقة حركته','1'],['🧮','Basic calculator','آلة حاسبة عادية','0'],['💡','Normal light switch','مفتاح إضاءة عادي','0']],'recognition')}<div id="feedback"></div>${nav(copy('Check my choices','تحقق من اختياراتي'),'recognition')}`;
case 2:return `<h1>${copy(...title[2])}</h1><p class="lede">${copy('AI is technology that can use information, find patterns and help computers do useful tasks.','الذكاء الاصطناعي تقنية يمكنها استخدام المعلومات والعثور على الأنماط ومساعدة أجهزة الحاسوب على أداء مهام مفيدة.')}</p><div class="pattern-machine"><div class="pattern-row"><div class="pattern-box">🐱 🐶<br>${copy('Examples','أمثلة')}</div><span>→</span><div class="pattern-box">🔎<br>${copy('Patterns','أنماط')}</div><span>→</span><div class="pattern-box">❓<br>${copy('Prediction','تنبؤ')}</div></div></div><p>${copy('What do YOU predict before the system reveals its result?','ما توقعك أنت قبل أن يعرض النظام نتيجته؟')}</p>${single([['🐱','Cat','قط'],['🐶','Dog','كلب'],['🤔','Not sure','لست متأكداً']],'patterns')}<div id="feedback"></div>${deep('Machine learning is one way AI systems are built. During training, examples can be called training data.','التعلّم الآلي إحدى الطرق التي تُبنى بها أنظمة الذكاء الاصطناعي. وأثناء التدريب يمكن تسمية الأمثلة بيانات تدريب.')}${nav(copy('Reveal','اعرض النتيجة'),'patterns')}`;
case 3:return `<h1>${copy(...title[3])}</h1><p class="lede">${copy('Fixed rules are often ordinary computing. Using information and patterns may involve AI.','القواعد الثابتة غالباً حوسبة عادية. وقد يتضمن استخدام المعلومات والأنماط ذكاءً اصطناعياً.')}</p>${single([['🧮','A calculator follows fixed rules','آلة حاسبة تتبع قواعد ثابتة'],['🗺️','A map predicts traffic from information','خريطة تتنبأ بحركة المرور من المعلومات'],['🎨','Mariam decides whether she likes a painting','مريم تقرر إن كانت تحب لوحة']],'distinguish')}<div id="feedback"></div>${nav(copy('Check','تحقق'),'distinguish')}`;
case 4:return `<h1>${copy(...title[4])}</h1><p class="lede">${copy('Different AI systems can use different abilities—and sometimes several together.','يمكن لأنظمة الذكاء الاصطناعي استخدام قدرات مختلفة، وأحياناً عدة قدرات معاً.')}</p><div class="grid two">${[['👁️','AI that sees','ذكاء اصطناعي يرى'],['💬','Words & voices','الكلمات والأصوات'],['🧩','Finds patterns','يجد الأنماط'],['✨','Creates','ينشئ'],['🤖','Helps machines act','يساعد الآلات على العمل'],['📊','Predicts & suggests','يتوقع ويقترح']].map(x=>`<article class="world-card"><span class="icon">${x[0]}</span><b>${copy(x[1],x[2])}</b></article>`).join('')}</div><div class="feedback info"><strong>IoT</strong>${copy('Connected devices can collect and share information. AI can use that information, but IoT itself is not AI.','يمكن للأجهزة المتصلة جمع المعلومات ومشاركتها. يمكن للذكاء الاصطناعي استخدام تلك المعلومات، لكن إنترنت الأشياء ليس هو الذكاء الاصطناعي.')}</div>${deep('Machine learning can sit underneath vision, language, generation, prediction and robotics. These capability worlds can overlap.','يمكن أن يدعم التعلّم الآلي الرؤية واللغة والتوليد والتنبؤ والروبوتات، وقد تتداخل هذه القدرات.')}${nav()}`;
case 5:return `<span class="sim-label">SIMULATION | محاكاة</span><h1>${copy(...title[5])}</h1><p class="lede">${copy('People give a machine-learning system examples. It uses them to find patterns that help it make a prediction.','يعطي الناس نظام التعلّم الآلي أمثلة. يستخدمها للعثور على أنماط تساعده على إصدار تنبؤ.')}</p><div class="pattern-machine"><div class="pattern-row"><div class="pattern-box">🍎 🍎 🍎<br>${copy('Examples','أمثلة')}</div><span>→</span><div class="pattern-box">🧩<br>${copy('Patterns','أنماط')}</div><span>→</span><div class="pattern-box">🍏 ?<br>${copy('Prediction','تنبؤ')}</div></div></div><p>${copy('Why might a green apple be harder after only red-apple examples?','لماذا قد تكون التفاحة الخضراء أصعب بعد أمثلة تحتوي على تفاح أحمر فقط؟')}</p>${single([['📚','The examples were too limited','الأمثلة كانت محدودة'],['😴','The AI got tired','تعب الذكاء الاصطناعي'],['🙅','The AI dislikes green','الذكاء الاصطناعي لا يحب الأخضر']],'train')}<div id="feedback"></div>${deep('People choose the examples, labels and task. A system can also be limited by the choices people designed for it.','يختار الناس الأمثلة والتسميات والمهمة، وقد يتقيد النظام بالخيارات التي صممها الناس له.')}${nav(copy('Check','تحقق'),'train')}`;
case 6:return `<span class="sim-label">SIMULATION | محاكاة</span><h1>${copy(...title[6])}</h1><div class="feedback warn"><strong>${copy('AI says:','يقول الذكاء الاصطناعي:')}</strong>${copy('“The Moon is bigger than Earth.”','«القمر أكبر من الأرض.»')}</div>${single([['🔎','Check it','أتحقق منها'],['✅','Believe it because AI said it','أصدقها لأن الذكاء الاصطناعي قالها'],['🚫','Never trust AI','لا أثق بالذكاء الاصطناعي أبداً']],'verify')}<div id="feedback"></div><div class="grid two"><article class="evidence-card"><strong>Earth | الأرض</strong><p>≈ 12,742 km</p></article><article class="evidence-card"><strong>Moon | القمر</strong><p>≈ 3,475 km</p></article></div>${deep('An AI system can produce a confident-sounding false answer. Some people call this a hallucination. Confidence is not proof.','قد ينتج نظام الذكاء الاصطناعي إجابة خاطئة تبدو واثقة. يسمي بعض الناس ذلك هلوسة. الثقة ليست دليلاً.')}${nav(copy('Check my choice','تحقق من اختياري'),'verify')}`;
case 7:return `<h1>${copy(...title[7])}</h1><div class="rule-row"><span>🧠 ${copy('Think first','أفكر أولاً')}</span><span>🔎 ${copy('Check important answers','أتحقق من الإجابات المهمة')}</span><span>🔐 ${copy('Keep private things private','أحافظ على معلوماتي الخاصة')}</span></div><p>${copy('Which information should stay private in this practice scenario?','أي معلومات يجب أن تبقى خاصة في هذا السيناريو التدريبي؟')}</p>${multi([['🐢','Favourite animal','الحيوان المفضل','0'],['🎨','Favourite colour','اللون المفضل','0'],['🏠','Home address','عنوان المنزل','1'],['🔑','Password','كلمة المرور','1'],['🏫','School or identifying location','المدرسة أو موقع يحدد هويتك','1'],['📞','Phone number','رقم الهاتف','1']],'privacy')}<div id="feedback"></div>${deep('Before sharing information, ask whether the activity really needs it. If you are unsure, ask a trusted adult.','قبل مشاركة المعلومات، اسأل هل يحتاج النشاط إليها فعلاً. وإذا لم تكن متأكداً، اسأل شخصاً بالغاً موثوقاً.')}${nav(copy('Check privacy choices','تحقق من اختيارات الخصوصية'),'privacy')}`;
case 8:return mission();
case 9:return `<h1>${copy(...title[9])}</h1><p class="lede">${copy('You did it. Before we finish, think about what you discovered.','أكملت مهمتك. قبل أن ننتهي، فكر فيما اكتشفته.')}</p><div class="journey-map"><span>✓ ${copy('Find AI','أتعرف إلى الذكاء الاصطناعي')}</span><span>✓ ${copy('Understand it','أفهمه')}</span><span>✓ ${copy('Try it','أجرّبه')}</span><span>✓ ${copy('Check it','أتحقق')}</span><span>✓ ${copy('Use it wisely','أستخدمه بوعي')}</span></div><div class="passport"><article><h3>${copy('Safety Passport','جواز الأمان')}</h3>${pass('agency',copy('Think first','أفكر أولاً'))}${pass('verification',copy('Check important answers','أتحقق من الإجابات المهمة'))}${pass('privacy',copy('Keep private things private','أحافظ على معلوماتي الخاصة'))}</article><article><h3>${copy('Skills Passport','جواز المهارات')}</h3>${pass('recognition',copy('Recognise AI','أتعرف إلى الذكاء الاصطناعي'))}${pass('patterns',copy('Examples & patterns','الأمثلة والأنماط'))}</article></div><div class="mental-model"><span>${copy('People','الناس')}</span><span>→</span><span>${copy('Information & examples','المعلومات والأمثلة')}</span><span>→</span><span>AI</span><span>→</span><span>${copy('Result','النتيجة')}</span><span>→</span><span>${copy('People think & check','الناس يفكرون ويتحققون')}</span></div><div class="feedback info"><strong>${copy('You remain the thinker. AI remains the tool.','أنت تفكر وتقرر. والذكاء الاصطناعي أداة تساعدك.')}</strong></div>${nav(copy('Return to my journey','العودة إلى رحلتي'),'finish')}`}}
function mission(){const s=state.missionStep;const q=[
[copy('Which could be AI help in the garden?','أي مما يلي يمكن أن يكون مساعدة بالذكاء الاصطناعي؟'),[['📷','Look for patterns in plant pictures','البحث عن أنماط في صور النباتات'],['📏','Measure with a ruler','القياس بالمسطرة'],['🚰','Turn a normal tap on','فتح صنبور عادي']],'m0'],
[copy('What would help the system learn useful plant patterns?','ما الذي يساعد النظام على اكتشاف أنماط مفيدة للنباتات؟'),[['🌿','Useful examples of different plants','أمثلة مفيدة لنباتات مختلفة'],['💡','A brighter screen','شاشة أكثر سطوعاً'],['💪','Tell it to try harder','نطلب منه أن يحاول أكثر']],'m1'],
[copy('AI says: “This plant definitely needs more water.” What should you do?','يقول الذكاء الاصطناعي: «هذه النبتة تحتاج بالتأكيد إلى مزيد من الماء». ماذا تفعل؟'),[['🔎','Check more information','أتحقق من معلومات إضافية'],['💧','Water it immediately','أسقيها فوراً'],['🚫','Never use AI','لا أستخدم الذكاء الاصطناعي أبداً']],'m2'],
[copy('The soil is already very wet. What should YOU decide?','التربة رطبة جداً بالفعل. ماذا تقرر أنت؟'),[['✋','Do not water it yet','لا أسقيها الآن'],['💧','Water it because AI said so','أسقيها لأن الذكاء الاصطناعي قال ذلك'],['🤖','Let AI decide','أدع الذكاء الاصطناعي يقرر']],'m3'],
[copy('Practice scenario: the tool asks for your full name, school and home address to save the result.','سيناريو تدريبي: تطلب الأداة اسمك الكامل ومدرستك وعنوان منزلك لحفظ النتيجة.'),[['🔐','Keep it private; the task does not need it','أحافظ عليها خاصة؛ المهمة لا تحتاجها'],['📤','Share it all','أشاركها كلها'],['🤷','Share it because AI asked','أشاركها لأن الذكاء الاصطناعي طلبها']],'m4']][s];
return `<h1>${copy(...title[8])}</h1><p class="lede">🌱 ${copy('School Garden Challenge','تحدي حديقة المدرسة')} · ${s+1}/5</p><p><strong>${q[0]}</strong></p>${single(q[1],q[2])}<div id="feedback"></div><div class="feedback info">${copy('Your decision matters. AI can help investigate; evidence and people guide the final action.','قرارك مهم. يمكن للذكاء الاصطناعي المساعدة في الاستكشاف، لكن الأدلة والناس يوجهان القرار النهائي.')}</div>${nav(copy(s===4?'Complete mission':'Continue mission',s===4?'أكمل المهمة':'تابع المهمة'),'mission')}`}
function pass(k,label){const v=state.evidence[k];return `<p><span class="status-chip">${v==='independent'?copy('Demonstrated','تم الإثبات'):v==='supported'?copy('With support','بدعم'):copy('Not yet','لم يثبت بعد')}</span> ${label}</p>`}
function chosen(key){const x=$(`[data-single="${key}"].selected`);return x?+x.dataset.i:null}
function feedback(t,w=false){const f=$('#feedback');if(f)f.innerHTML=`<div class="feedback ${w?'warn':''}">${t}</div>`}
function complete(advance=true){if(!state.done.includes(state.stage))state.done.push(state.stage);if(advance&&state.stage<9)state.stage++;save();render()}
function act(a){if(a==='back'){state.stage=Math.max(0,state.stage-1);save();render();return}if(a==='next'){complete();return}
if(a==='recognition'){const e=$$('[data-multi="recognition"]'),ok=e.length&&e.every(x=>x.classList.contains('selected')===(x.dataset.answer==='1'));if(ok){mark('recognition');feedback(copy('<strong>Good thinking.</strong> Not every machine is AI.','<strong>تفكير جيد.</strong> ليست كل آلة ذكاءً اصطناعياً.'));complete(false)}else feedback(copy('Look again at fixed-rule tools.','راجع الأدوات التي تعمل بقواعد ثابتة.'),true);return}
if(a==='patterns'){if(chosen('patterns')===null){feedback(copy('Make your prediction first.','ضع توقعك أولاً.'),true);return}mark('patterns');feedback(copy('<strong>You explored machine learning.</strong> Examples can help a system find patterns. AI is a tool, not a person, and it can make mistakes.','<strong>لقد استكشفت التعلّم الآلي.</strong> يمكن للأمثلة مساعدة النظام في العثور على الأنماط. الذكاء الاصطناعي أداة وليس شخصاً وقد يخطئ.'));complete(false);return}
if(a==='distinguish'){const c=chosen('distinguish');if(c===1){feedback(copy('Yes. Predicting traffic from information may involve AI.','نعم. قد يتضمن التنبؤ بحركة المرور من المعلومات ذكاءً اصطناعياً.'));complete(false)}else feedback(copy('Look for the example using information and patterns rather than only a fixed rule or personal preference.','ابحث عن المثال الذي يستخدم المعلومات والأنماط بدلاً من قاعدة ثابتة أو تفضيل شخصي.'),true);return}
if(a==='train'){if(chosen('train')===0){mark('patterns');feedback(copy('Correct. Better examples can help performance, but do not guarantee correctness.','صحيح. قد تساعد الأمثلة الأفضل على تحسين الأداء لكنها لا تضمن الصحة.'));complete(false)}else feedback(copy('AI does not get tired or have likes and dislikes like a person.','الذكاء الاصطناعي لا يتعب ولا يملك ما يحبه أو يكرهه مثل الإنسان.'),true);return}
if(a==='verify'){if(chosen('verify')===0){mark('verification');feedback(copy('Correct. Confidence is not proof. Important answers deserve good evidence.','صحيح. الثقة ليست دليلاً. الإجابات المهمة تستحق أدلة جيدة.'));complete(false)}else feedback(copy('Do not automatically believe or reject AI. Check when it matters.','لا تصدق الذكاء الاصطناعي أو ترفضه تلقائياً. تحقق عندما يكون الأمر مهماً.'),true);return}
if(a==='privacy'){const e=$$('[data-multi="privacy"]'),ok=e.every(x=>x.classList.contains('selected')===(x.dataset.answer==='1'));if(ok){mark('privacy');feedback(copy('Correct. Keep private information private.','صحيح. حافظ على معلوماتك الخاصة.'));complete(false)}else feedback(copy('Private information can identify, contact or locate you, or give access to an account.','قد تكشف المعلومات الخاصة هويتك أو تتيح الاتصال بك أو تحديد موقعك أو الوصول إلى حسابك.'),true);return}
if(a==='mission'){const k='m'+state.missionStep,c=chosen(k);if(c===0){if(state.missionStep===0&&state.evidence.recognition==='not-yet')state.evidence.recognition=state.hints.mission?'supported':'independent';if(state.missionStep===1&&state.evidence.patterns==='not-yet')state.evidence.patterns=state.hints.mission?'supported':'independent';if(state.missionStep===2&&state.evidence.verification==='not-yet')state.evidence.verification=state.hints.mission?'supported':'independent';if(state.missionStep===3)state.evidence.agency=state.hints.mission?'supported':'independent';if(state.missionStep===4)state.evidence.privacy=state.hints.mission?'supported':'independent';if(state.missionStep<4){state.missionStep++;save();render()}else{state.missionStep=0;save();complete()} }else feedback(copy('Use the evidence, protect privacy, and keep the final decision with you.','استخدم الأدلة واحمِ الخصوصية وأبقِ القرار النهائي بيدك.'),true);return}
if(a==='finish'){state.completed=true;if(!state.done.includes(9))state.done.push(9);save();location.href='index.html#journey'}}
function wire(){$$('[data-single]').forEach(x=>x.onclick=()=>{$$(`[data-single="${x.dataset.single}"]`).forEach(y=>y.classList.remove('selected'));x.classList.add('selected')});$$('[data-multi]').forEach(x=>x.onclick=()=>x.classList.toggle('selected'));$$('[data-action]').forEach(x=>x.onclick=()=>act(x.dataset.action));$$('[data-goto]').forEach(x=>x.onclick=()=>{const target=+x.dataset.goto,max=Math.min(9,(state.done.length?Math.max(...state.done)+1:0));if(target<=max){state.stage=target;save();render()}else toast(copy('Complete the current journey first.','أكمل مسارك الحالي أولاً.'))})}
function renderDots(){const max=Math.min(9,(state.done.length?Math.max(...state.done)+1:0));$('#stageDots').innerHTML=title.map((_,i)=>`<li><button class="stage-dot ${i===state.stage?'active':''} ${state.done.includes(i)?'done':''}" data-goto="${i}" ${i>max?'disabled':''} aria-label="${copy('Stage','المرحلة')} ${String(i).padStart(2,'0')}">${String(i).padStart(2,'0')}</button></li>`).join('')}
async function loadCompanion(){if(state.companion==='none')return;const p=state.companion==='hamdan'?'assets/hamdan/hamdan_full_body.b64':'assets/hessa/hessa_full_body.b64';try{const r=await fetch(p);const b=(await r.text()).trim();$$('#stageCompanion,#companionImage').forEach(img=>img.src='data:image/webp;base64,'+b)}catch{}}
function toast(t){const x=$('#toast');x.textContent=t;x.hidden=false;setTimeout(()=>x.hidden=true,2200)}
function render(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';$('#langBtn').textContent=state.lang==='ar'?'English':'العربية';$('#ageLabel').textContent=state.age==='7-9'?'7–9':'10–12';$('#lessonTitle').textContent=copy('Lesson 1 — What Is AI?','الدرس 1 — ما هو الذكاء الاصطناعي؟');$('#progressFill').style.width=`${Math.round((state.stage+1)*10)}%`;$('#stageView').innerHTML=shell(stageBody(),state.stage===0);renderDots();wire();loadCompanion();const panel=$('#companionPanel');panel.hidden=state.companion==='none';if(!panel.hidden){$('#companionName').textContent=state.companion==='hamdan'?copy('Hamdan','حمدان'):copy('Hessa','حصه');$('#companionText').textContent=copy('I can give a thinking hint if you ask.','يمكنني إعطاؤك تلميحاً يساعدك على التفكير إذا طلبت.')}save()}
function setup(){const age=$('#ageMenu'),comp=$('#companionMenu');$('#ageBtn').onclick=()=>age.hidden=!age.hidden;$('#companionBtn').onclick=()=>comp.hidden=!comp.hidden;$$('[data-age]').forEach(b=>b.onclick=()=>{state.age=b.dataset.age;age.hidden=true;save();render()});$$('[data-companion]').forEach(b=>b.onclick=()=>{state.companion=b.dataset.companion;comp.hidden=true;save();render()});$('#langBtn').onclick=()=>{state.lang=state.lang==='en'?'ar':'en';save();render()};$('#listenBtn').onclick=()=>{if(!('speechSynthesis'in window)){toast(copy('Listen is not available in this browser.','الاستماع غير متاح في هذا المتصفح.'));return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#stageView').innerText);u.lang=state.lang==='ar'?'ar-AE':'en-GB';speechSynthesis.speak(u)};$('#hintBtn').onclick=()=>{const k=state.stage===8?'mission':({1:'recognition',2:'patterns',5:'patterns',6:'verification',7:'privacy'}[state.stage]||'general');state.hints[k]=true;save();$('#companionText').textContent=copy('What evidence, example or rule could help you decide?','ما الدليل أو المثال أو القاعدة التي قد تساعدك على اتخاذ القرار؟')}}
setup();render();