-- Resolve Supabase linter warning for authenticated SECURITY DEFINER functions.
-- The synchronization RPCs now execute as SECURITY INVOKER; explicit RLS policies enforce authorized child scope on every affected table.
create policy learning_state_authorized_insert on public.child_learning_state for insert to authenticated with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=child_learning_state.child_profile_id and a.adult_user_id=(select auth.uid())) and not exists(select 1 from public.child_profiles c where c.id=child_learning_state.child_profile_id and c.archived_at is not null));
create policy learning_state_authorized_update on public.child_learning_state for update to authenticated using(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=child_learning_state.child_profile_id and a.adult_user_id=(select auth.uid()))) with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=child_learning_state.child_profile_id and a.adult_user_id=(select auth.uid())) and not exists(select 1 from public.child_profiles c where c.id=child_learning_state.child_profile_id and c.archived_at is not null));
create policy mission_progress_authorized_insert on public.mission_progress for insert to authenticated with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=mission_progress.child_profile_id and a.adult_user_id=(select auth.uid())));
create policy mission_progress_authorized_update on public.mission_progress for update to authenticated using(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=mission_progress.child_profile_id and a.adult_user_id=(select auth.uid()))) with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=mission_progress.child_profile_id and a.adult_user_id=(select auth.uid())));
create policy passport_evidence_authorized_insert on public.passport_evidence for insert to authenticated with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=passport_evidence.child_profile_id and a.adult_user_id=(select auth.uid())));
create policy passport_evidence_authorized_update on public.passport_evidence for update to authenticated using(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=passport_evidence.child_profile_id and a.adult_user_id=(select auth.uid()))) with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=passport_evidence.child_profile_id and a.adult_user_id=(select auth.uid())));
create policy achievements_authorized_insert on public.child_achievements for insert to authenticated with check(exists(select 1 from public.adult_child_authorizations a where a.child_profile_id=child_achievements.child_profile_id and a.adult_user_id=(select auth.uid())));
grant insert,update on public.child_learning_state to authenticated;
grant insert,update on public.mission_progress to authenticated;
grant insert,update on public.passport_evidence to authenticated;
grant insert on public.child_achievements to authenticated;
alter function public.sync_child_learning_state(uuid,jsonb,bigint) security invoker;
alter function public.get_child_cloud_passport(uuid) security invoker;